[project]
name = "temp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "japanize-matplotlib>=1.1.3",
    "jupyter>=1.1.1",
    "jupyterlab>=4.4.0",
    "lab>=8.4",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
]
